# Generated by Django 3.2.3 on 2021-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210601_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='employee',
        ),
        migrations.AddField(
            model_name='todo',
            name='employee',
            field=models.ManyToManyField(to='core.Employee'),
        ),
    ]
