# Generated by Django 3.2.3 on 2021-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210601_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.ManyToManyField(to='core.Status'),
        ),
    ]
